# Generated by Django 5.1.6 on 2025-03-02 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userproject',
            old_name='finished_datee',
            new_name='finished_date',
        ),
    ]
