# Generated by Django 5.1.6 on 2025-03-10 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_projectlanguage_language_and_more'),
        ('users', '0002_rename_finished_datee_userproject_finished_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproject',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_projects', to='project.project'),
        ),
    ]
