# Generated by Django 5.1.6 on 2025-02-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproject',
            name='finished_datee',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
