# Generated by Django 5.1.6 on 2025-03-12 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('style', '0003_delete_useractivestyle'),
        ('users', '0003_alter_userproject_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='background_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='background_projects', to='style.style'),
        ),
        migrations.AddField(
            model_name='user',
            name='nickname_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nickname_projects', to='style.style'),
        ),
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Обо мне'),
        ),
    ]
