# Generated by Django 5.1.6 on 2025-03-14 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('style', '0004_rename_price_style_price_in_coin_and_more'),
        ('users', '0004_user_background_profile_user_nickname_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='background_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='background_profile', to='style.style'),
        ),
    ]
