# Generated by Django 5.1.6 on 2025-03-25 18:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_userproject_code_userprogress_userskill'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprogress',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='ProgressLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_change', models.IntegerField(default=0)),
                ('stars_change', models.IntegerField(default=0)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
