# Generated by Django 5.1.6 on 2025-03-27 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_userprogress_options_alter_userprogress_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='userprogress',
            options={'verbose_name': 'Прогресс пользователя', 'verbose_name_plural': 'Прогресс пользователей'},
        ),
        migrations.AlterModelOptions(
            name='userproject',
            options={'verbose_name': 'Проект пользователя', 'verbose_name_plural': 'Проекты пользователя'},
        ),
        migrations.AlterModelOptions(
            name='userskill',
            options={'verbose_name': 'Навык пользователя', 'verbose_name_plural': 'Навыки пользователей'},
        ),
    ]
