# Generated by Django 5.1.6 on 2025-02-27 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_open', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('prev_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_projects', to='project.project')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maps', to='project.project')),
            ],
            options={
                'verbose_name': 'Карта проектов',
                'verbose_name_plural': 'Карта проектов',
            },
        ),
        migrations.CreateModel(
            name='ProjectPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_x', models.FloatField()),
                ('position_y', models.FloatField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='project.project')),
            ],
            options={
                'verbose_name': 'Позиция проекта',
                'verbose_name_plural': 'Позиции проектов',
            },
        ),
    ]
