# Generated by Django 5.1.6 on 2025-03-15 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_projectmap_is_completed_projectmap_is_open'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmap',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='projectmap',
            name='is_open',
        ),
    ]
