# Generated by Django 5.1.6 on 2025-03-27 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_remove_project_time_to_leave_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='new_time_to_leave',
            new_name='time_to_leave',
        ),
    ]
