# Generated by Django 5.1.6 on 2025-03-22 08:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_projectlanguage_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='time_to_leave',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
