# Generated by Django 5.1.6 on 2025-04-07 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_rename_new_time_to_leave_project_time_to_leave'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectlanguage',
            options={'ordering': ['project__name'], 'verbose_name': 'Язык для проекта', 'verbose_name_plural': 'Языки для проектов'},
        ),
        migrations.AddConstraint(
            model_name='projectlanguage',
            constraint=models.UniqueConstraint(fields=('project', 'language'), name='unique_project_language'),
        ),
    ]
