# Generated by Django 5.1.6 on 2025-03-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_project_time_to_leave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='coins',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='difficulty',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='experience',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
