# Generated by Django 5.1.6 on 2025-03-23 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_project_coins_alter_project_difficulty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='coins',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='difficulty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='experience',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
