# Generated by Django 5.1.6 on 2025-04-07 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_projectlanguage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='compiler_name',
            field=models.CharField(default='python', max_length=100, verbose_name='Имя для компилятора'),
            preserve_default=False,
        ),
    ]
