# Generated by Django 5.1.6 on 2025-04-07 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_language_compiler_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='compiler_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Имя для Judge0'),
        ),
    ]
