# Generated by Django 5.1.6 on 2025-04-04 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0002_test'),
        ('project', '0003_rename_new_time_to_leave_project_time_to_leave'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codeexecution',
            options={'verbose_name': 'Компилятор', 'verbose_name_plural': 'Компиляторы'},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': 'Тест', 'verbose_name_plural': 'Тесты'},
        ),
        migrations.AddField(
            model_name='codeexecution',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.project'),
        ),
    ]
