# Generated by Django 5.1.6 on 2025-04-08 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0003_alter_codeexecution_options_alter_test_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeexecution',
            name='language',
            field=models.CharField(),
        ),
    ]
