# Generated by Django 5.1.6 on 2025-03-28 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_remove_comment_project_comment_user_project'),
        ('project', '0003_rename_new_time_to_leave_project_time_to_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='project',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='project.project'),
        ),
    ]
