# Generated by Django 5.1.6 on 2025-03-28 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_comment_project'),
        ('users', '0009_alter_user_options_alter_userprogress_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='project',
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userproject'),
        ),
    ]
