# Generated by Django 5.1.6 on 2025-04-04 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0005_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='like',
            options={'verbose_name': 'Лайк', 'verbose_name_plural': 'Лайки'},
        ),
    ]
