# Generated by Django 5.1.6 on 2025-03-13 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('style', '0003_delete_useractivestyle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='style',
            old_name='price',
            new_name='price_in_coin',
        ),
        migrations.AddField(
            model_name='style',
            name='price_in_stars',
            field=models.IntegerField(default=0),
        ),
    ]
