# Generated by Django 5.1.6 on 2025-03-23 17:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('style', '0004_rename_price_style_price_in_coin_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userstyle',
            constraint=models.UniqueConstraint(fields=('user', 'style'), name='unique_user_style'),
        ),
    ]
